### ISSUE TITLE
Data Attribute for Individual Cells like a Word ID

### ISSUE THREAD

**Issue by thmsdnnr** [kbrtrm/xword.io#10]
(quoted from our e-mail convo so we can document work on this and tie it to a PR if we decide to do it...)
# do we still want to do it?

> Another thing on my mind, if we had another data attribute on individual cells that was something like a word ID (there'd be two word IDs per cell, one for H, one for V)—that would make the UI task highlight the current full word super easy. I'm thinking of solve mode right now, but of course, the idea extends to build mode, too.

Ah, gotcha, so like instead of just having the data-row and data-col attributes for each cell, we also store a unique ID for vertical and horizontal words ON the cells itself, so that all cells with a matching data-word-id make up a word unit? So kind of like putting the data that we grab and put into wordPosDict back into the cells themselves when we render them? Currently I'm just storing them in wordPosDict behind the scenes and then running logic on that object internally. Are you saying update the div data attributes as we go so in this picture for instance:

http://i.imgur.com/RUppwa7.png

each div cell for CARING has a data-H="UNIQUE_ID_FOR_CARING" 

and every cell EXCEPT the last one has a blank data-V, and the last one has a data-V that is "UNIQUE_ID_FOR_GOAL"?

To simplify it, we could make the UNIQUE_IDs the 1C-H or 5C-H or 5C-V, since those are already the keys in the wordPosDict object, and they contain some embedded info that might be useful for your calcs too?

> Spot on, does this seem advantageous to you?

I think so. My only concern is keeping changes in sync: so my code letting your code know when something changes through the UI.

So for instance, in the UI editor, someone changes the length of a horizontal word, which changes the number of cells that have a given data-H ID. 

On my end, I delete the data-H ID from the cell and modify the wordPosDict object, but I still need to call something in your code to let you know to respond to that change, right? Like to re-evaluate which cells should have which styling, or to remove/add a class?

That's kind of how I was thinking about the editor: rules for the way we format a board, the user interacts with the state in the ways we let them, modifying the board state, and then every time they make a change, it changes the state of the component, and React automatically reevaluates those rules and displays the updated component.

OR: there's maybe two places we can evaluate what the code looks like and style it: you can either read the wordPosDict directly before we render it, and then apply the styling rules to the board before it gets mounted on the DOM, or I can put parameters from the object into the corresponding div cells, and you can change the classes to change the appearance after we render each cell. 

I think either way works, and I'm not sure of the advantages/disadvantages. I think that was the only thing I was thinking about: how can we make our code talk to one another to say 

"hey, I updated some stuff, you should reevaluate it and display it differently"

**Comment by kbrtrm** [comment]
I think we do, unless we have some other way or data right now that can help us track this. For me, on the UI side, this will help us contextually identifying current word on board / clue in list:

![img_4006](https://cloud.githubusercontent.com/assets/5074848/23216464/aa29141a-f8db-11e6-9193-14b0c00c67ab.JPG)

**Comment by thmsdnnr** [comment]
Cool! For simplicity sake, is it acceptable to make it like data-VPK and
data-HPK (for vertical and horizontal primary key, respectively), and then
make that key the same value as the object key in wordPosDict? So, for
instance, 01-01-H word has data-HPK=01-01-H for all letters. 01-01-V word
has data-VPK=01-01-V for all its letters.

That just makes it one less thing to have to parse and if we change our
keys down the road, it'll change here as well, so less stuff to keep in
sync. Would that work?

**Comment by kbrtrm** [comment]
YEP

**Comment by thmsdnnr** [comment]
Cool. I fixed this in Pull Request #11 too. When you verify that fix & the other open issue, can you close em' up? Thanks!

**Comment by kbrtrm** [comment]
Working b-e-a-u-tifully
