### ISSUE TITLE
Need to add the bootstrap & jQuery assets

### ISSUE THREAD

**Issue by thmsdnnr** [kbrtrm/xword.io#5]
We still need to add bootstrap.min.css to assets/css in our project, or use the CDN? We link to the stylesheet here `<link rel="stylesheet" href="/assets/css/bootstrap.min.css">` but for some reason it didn't show up when I pulled it from your repo. Maybe you have it locally but it didn't get put in the commit?

I think the things we need added (or taken from a CDN) are the bootstrap.min.js, the bootstrap.min.css, and then the jQuery JS (which I think we need to put in the header before the bootstrap.min.js...I was getting weird behavior when I was trying to drag and drop all this stuff). I was going to just add it myself but your screenshots look great and I figured I'd let you just do it since you already know what you're doing on your end! :)

**Comment by kbrtrm** [comment]
Did I move the jQuery assets in the ejs templates? I can't remember.
I've added the bootstrap assets.

**Comment by thmsdnnr** [comment]
I think you're good — everything looks fine on my end (except the little
mobile nav dropdown menu doesn't render anything but I think it's just not
implemented yet?). I don't know actually what the bootstrap.js is for and
if we need it.

**Comment by kbrtrm** [comment]
Yes, I was just being lazy... the responsive nav requires the bootstrap.js stuff to work.

**Comment by thmsdnnr** [comment]
Haha not lazy. I'm trying to figure out the React stuff still, and whether
or not it makes sense to use it. There are some pros and cons. Not sure if
there's a performance benefit necessarily, since the crossword isn't super
DOM-update heavy. I sort of feel like it's overdoing it a little bit
sometimes. Maybe start really small and add on features like React Router
or whatever to make it a single-page app as we go, and if necessary?

**Comment by kbrtrm** [comment]
Sounds like a plan!

**Comment by thmsdnnr** [comment]
Oops, forgot to say this was fixed :) thanks!!
